name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        go build -v ./...
        cd cmd/cilium
        go build

    - name: Test
      run: |
        go test -v ./...

    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: cilium
        path: cmd/cilium/cilium
